server:
  port: ${SERVER_PORT}
  error:
    include-message: always

spring:
  application:
    name: ${APPLICATION_NAME}

integration:
  apk:
    base-url: ${APK_URL}
    username: ${APK_USERNAME}
    password: ${APK_PASSWORD}
  ni-fi:
    base-url: ${NIFI_URL}
    username: ${NIFI_USERNAME}
    password: ${NIFI_PASSWORD}
    create-limits:
      path: ${NIFI_CREATE_LIMITS_PATH}
    upsert-limits:
      path: ${NIFI_UPSERT_LIMITS_PATH}
  technolog:
    soap-url: ${TECH_SOAP_URL}
    username: ${TECH_USERNAME}
    password: ${TECH_PASSWORD}

logging:
  level:
    su.petrosoft.apk_ack_integration: DEBUG
